export const defaultPlotCharacters = [
  {
    plotcharactername: "Gandalf the Debugger",
    personality: 99,
    charStoryKeywords: [
      "The Floating Tower",
      "Member of the Blades",
      "Wizards",
      "Fate",
      "Adventure",
      "Magic",
    ],
    pictureKeywords: [
      "medievalfantasy",
      "story",
      "adventure",
      "TheFloatingTower",
    ],
    aiPictureUrls: [],
    fullStories: [],
    selectedUserOptions: [],
  },
  {
    plotcharactername: "Peter Quincy Taggart",
    personality: 50,
    charStoryKeywords: [
      "Space",
      "Sci-fi",
      "Comedy",
      "Starship",
      "Science",
      "Humour",
    ],
    pictureKeywords: ["scifi", "story", "space", "stars"],
    aiPictureUrls: [],
    fullStories: [],
    selectedUserOptions: [],
  },
  {
    plotcharactername: "Detective Harper Blythe",
    personality: 85,
    charStoryKeywords: [
      "The Silent Witness",
      "Mystery",
      "Detective",
      "Secrets",
      "Suspense",
      "Puzzle",
    ],
    pictureKeywords: ["noir", "detective", "modern", "city"],
    aiPictureUrls: [],
    fullStories: [],
    selectedUserOptions: [],
  },
  {
    plotcharactername: "Dave 'The Schemer' Reynolds",
    personality: 75,
    charStoryKeywords: [
      "The Great Couch Caper",
      "Comedy",
      "Chaos",
      "Friendship",
      "Ridiculous Plans",
      "Talking animals",
    ],
    pictureKeywords: ["comedy", "adventure", "modern", "funny"],
    aiPictureUrls: [],
    fullStories: [],
    selectedUserOptions: [],
  },
  {
    plotcharactername: "Major Elena 'Shadow' Carter",
    personality: 12,
    charStoryKeywords: [
      "Operation Shadow Strike",
      "Military",
      "Action",
      "Covert Mission",
      "High Stakes",
      "Combat",
    ],
    pictureKeywords: ["military", "action", "tactical", "intense"],
    aiPictureUrls: [],
    fullStories: [],
    selectedUserOptions: [],
  },
];
