export const generatedStoryPictureList = (plotCharacter) => {
  let result = "";
  for (let i = 0; i < plotCharacter.aiPictureUrls.length; i++) {
    const element = plotCharacter.aiPictureUrls[i];
    result += `<li key="${element}"><a href="${element}" target="_blank">${
      i + 1
    }. picture</a></li>`;
  }
  return result;
};

export const welcomeTextCreator = (user) => {
  let welcomeText = `Dear ${user.username}, we are happy to send you the story of your choice, generated by the GEMINI AI! See how the historical events unfold based on your decisions and responses.`;
  return welcomeText;
};

export const generatedStoryTextCreator = (plotCharacter) => {
  let result = `<h2>Starting scene:<h2>
    <h3>${plotCharacter.fullStories[0]}<h3>`;

  for (let i = 0; i < plotCharacter.selectedUserOptions.length; i++) {
    result += `<h3 key=${plotCharacter.selectedUserOptions[i]}>Your choice: ${plotCharacter.selectedUserOptions[i]}</h3>`;
    result += `<h4 key=${plotCharacter.fullStories[i + 1]}>${
      plotCharacter.fullStories[i + 1]
    }</h4>`;
  }
  return result;
};
